### ISSUE TITLE
[Feature suggestion] `--verbose` flag

### ISSUE THREAD

**Issue by jodeleeuw** [pushkin-consortium/pushkin-cli#109]
I think the default user experience of running the CLI should be a relatively quiet install. A progress bar (e.g. [cli-progress](https://www.npmjs.com/package/cli-progress)) would be user friendly. The wall of text that currently gets generated is probably a bit overwhelming for a new user. For debugging, a `--verbose` flag could turn back on the outputs currently generated.

**Comment by jkhartshorne** [comment]
@jessestorbeck -- this might actually be a pretty good CLI task for you. The cli package we use makes it pretty easy to parse flags. So you just have to add code to check for that flag and use it to set a variable (a good name for it would be "verbose"). Then every place we currently use `console.log`, you would first check to see if `verbose==true` and only print if it is. Unless it's something very important (like an error or a warning or ... something else very important). 

I'm sure the package has a way of instituting a status bar, but I haven't checked.

If it'd be helpful, schedule a meeting with me to discuss. In particular, you might have some questions about the CLI package we use.

**Comment by jessestorbeck** [comment]
@jkhartshorne -- I agree this seems pretty doable for me.
