### ISSUE TITLE
Error: Cannot find module './logo512.png'

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin-cli#53]
@jkhartshorne 
I'm consistently running into the issue with logo512.png being piped in as the logo for the experiments, and despite moving a copy to the assets/images/quiz folder, additionally updating the individual experiment config files, and re-running pushkin prep after armageddon, it still insists "Error: Cannot find module './logo512.png'". Not sure if this is why, but the experiments.js file doesn't get information piped in like it did before: is this now expected behavior? Any thoughts on what else I might need to edit to fix this?

Attached is what I see at localhost:
<img width="1033" alt="Screen Shot 2020-07-01 at 1 40 15 PM" src="https://user-images.githubusercontent.com/37002158/86275199-e89d3600-bba0-11ea-9be8-5e98fb702b44.png">

**Comment by jkhartshorne** [comment]
That is not expected. I’ll have to look into that.

**Comment by jkhartshorne** [comment]
The CLI has been updated. It should work now.
