### ISSUE TITLE
Excess files/folders being generated when building pushkin default site

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin-cli#54]
The following are being generated in the pushkin default site:

- "_MACOSX" folders within each experiment's folder (apparently these are "resource forks" from zip files; not sure what caused these to be added but it doesn't seem to me like these are needed)
- A file called and containing nothing but [], living in the root folder
- Another file in the root folder containing [], with the title "[{"name":"Mind_api","mountPath":"Mind"},{"name":"Vocab_api","mountPath":"Vocab"},{"name":"WhichEnglish_api","mountPath":"WhichEnglish"}]"

**Comment by jkhartshorne** [comment]
So it looks like the issue wasn't actually in the CLI but comes from how the release for the site template is constructed. If I zip up the files in Finder, you get random extra MacOS files. But if I zip them up in terminal, the problem goes away. So this is something to be careful about in making new releases of site and experiment templates.

**Comment by jkhartshorne** [comment]
Actually, `pushkin prep` also creates a '[]' file.
