### ISSUE TITLE
Fails to update experiments when changed

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin-cli#65]
Wasn't sure if this is a CLI thing or more of a default site template thing:

This shows how the change I made to the experiment ("Hello PLANET") successfully builds in the experiment folder, but the front-end/build/js/2.cace40f9.chunk.js file that from what I can tell relates to asset-manifest.json is not changed ("Hello World").
<img width="1440" alt="Screen Shot 2020-07-23 at 4 09 03 PM" src="https://user-images.githubusercontent.com/37002158/88335324-1dfcf580-cd01-11ea-852b-d6fa0233ff55.png">

I also tried running yarn run build in front-end to see if it helped, but it still re-builds with "Hello World."

After changing the experiment, even if I change it back to the original Hello World, I get these internal server errors:
<img width="1438" alt="Screen Shot 2020-07-23 at 4 17 16 PM" src="https://user-images.githubusercontent.com/37002158/88335593-91066c00-cd01-11ea-86f4-59bbbfb7835f.png">

**Comment by jkhartshorne** [comment]
So ... the node package I was using for interacting with docker has really lousy documentation. It said that the function I was using built _and_ started docker containers. Actually, it didn't do the builds, only the starting. So updates weren't getting pushed. I fixed that in the CLI. Should work now.
