### ISSUE TITLE
Error running pushkin install (site) in Pushkin 0.9.0 - appears to be a release issue?

### ISSUE THREAD

**Issue by conbainbridge** [pushkin-consortium/pushkin-cli#68]
<img width="614" alt="Screen Shot 2020-07-24 at 9 46 23 AM" src="https://user-images.githubusercontent.com/37002158/88415371-62919b00-cdac-11ea-9557-8da8490186d3.png">

**Comment by jkhartshorne** [comment]
@conbainbridge try it now. 

There was a problem with the zip file for the most recent site release. To make a release, you need to upload a zip of the repo called "Archive.zip". 
 You can see from this screenshot that it wasn't uploaded successfully:

![Screen Shot 2020-07-24 at 1 43 19 PM](https://user-images.githubusercontent.com/6118115/88419838-d5524480-cdb3-11ea-8112-e0f658c6bc2f.png)

Incidentally, the problem we were having before with the "__Mac" files was from how the archive was made. If you make it in Finder, you get those extra Mac files. Here's the procedure:

1. Download the repo as a zip file. (You could use your local copy, but you have to make sure to exclude all the node_packages and build folders; easier to just download clean.)

2. Go into terminal and unzip the file (`unzip [filename]`). Then cd into the folder and run `zip -r Archive.zip *`. Then go to Github and make a new version. In choosing a release number, be sure to use semantic versioning (there's a link from the 'make a release' page). Be sure to attach Archive.zip.

Connie - can you please update the advanced/developer docs with this information? Then assign me the pull request so I can make any edits? Thanks!

**Comment by conbainbridge** [comment]
@jkhartshorne Now I'm getting an error on Pushkin start (appears to be an error yarn throws), not sure if this is related so commenting on this issue for now!
<img width="620" alt="Screen Shot 2020-07-24 at 4 29 21 PM" src="https://user-images.githubusercontent.com/37002158/88433042-5b2dba00-cdcb-11ea-820e-6c316167a0d0.png">

**Comment by jkhartshorne** [comment]
This is for a self-paced reading experiment? Have you updated that
experiment template to take advantage of yalc? The change to yalc was
actually specifically to deal with this issue, and I haven't seen it since.

**Comment by conbainbridge** [comment]
Yep, this issue is no longer coming up for me! I'll double check I don't have other outstanding issues open that were before all the updates.
