### ISSUE TITLE
Problems installing pushkin-cli?

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin-cli#7]
Joshuas-Air:TrialWebsites jkhartshorne$ npm install -g pushkin-cli
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-7SljTRm6ukY7bOa4CjchPqtx7EM= integrity checksum failed when using sha1: wanted sha1-7SljTRm6ukY7bOa4CjchPqtx7EM= but got sha512-1MkrZNvWTKCaigbn+W15elq2BB/L22nqrSY5DKlo3X6+vclJm8Bb5djXJBmEX6fS3+zCh/F4VBK5Z2KxJt4s2Q==. (2272 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-BsJ3IYRU7CiN93raVKA7hwKqy50= integrity checksum failed when using sha1: wanted sha1-BsJ3IYRU7CiN93raVKA7hwKqy50= but got sha512-JhBl0skXjUPCFH7x6x61gQxrKyXsxB5gcgePLZCwfyCGGsTISMoIeObbrvVeP6Xmyaudw4TT43qV2Gz+iyd2oQ==. (4200 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-Sl7Hxk364iw6FBJNus3uhG2Ay8Q= integrity checksum failed when using sha1: wanted sha1-Sl7Hxk364iw6FBJNus3uhG2Ay8Q= but got sha512-eTVLrBSt7fjbDygz805pMnstIs2VTBNkRm0qxZd+M7A5XDdxVRWO5MxGBXZhjY4cqLYLdtrGqRf8mBPmzwSpWQ==. (7494 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
/usr/local/bin/pushkin -> /usr/local/lib/node_modules/pushkin-cli/build/index.js
+ pushkin-cli@0.0.7
added 273 packages in 12.39s

**Comment by jkhartshorne** [comment]
It still works, but I don't feel like we should be getting all these warnings...

**Comment by sc8ing** [comment]
There's an issue for npm about this: https://github.com/npm/npm/issues/17146. It doesn't seem like anything we're doing wrong.
