### ISSUE TITLE
`pushkin install experiment` should ask for "Which experiment template"

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin-cli#73]
The command `pushkin install experiment` (Version 1.1.3) currently asks the following: 

```
? Which site template do you want to use? (Use arrow keys)
```

I believe it should ask, "Which **experiment** template do you want to use?"

**Comment by jkhartshorne** [comment]
I'll take this one.

**Comment by conbainbridge** [comment]
@jkhartshorne Already in my pull request
