### ISSUE TITLE
New experiment templates are not available in `pushkin install experiment`

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin-cli#76]
## Summary
New experiment templates are not available in `pushkin install experiment`

## Steps to Reproduce
```bash
$ pushkin armageddon
$ yarn global upgrade pushkin-cli
$ pushkin -V # should show 1.1.4
$ mkdir testing_templates && cd testing_templates/
$ pushkin install site
$ pushkin install experiment 
```
## Expected Results
I should be able to select the lexical decision and grammaticality judgment templates using the arrow keys.

## Actual Results
No options are given when using any of the area keys. The *basic* experiment template installs normally, however. (Running `pushkin prep` and `pushkin start;` after installing the *basic* template also works.)

## Other Information
**pushkin-cli version:** 1.1.4 
**OS:** Ubuntu 18.04.4 LTS (local machine; not in an instance on AWS or a VM)

**Comment by jkhartshorne** [comment]
@parkerrobbins can you please add a screenshot of what you see when you try to install an experiment?

**Comment by jkhartshorne** [comment]
I'm seeing this as well. Which is strange.

**Comment by jkhartshorne** [comment]
I think it has something to do with a failed `yarn publish`. I'm publishing a new version. Let's see if that works.

**Comment by jkhartshorne** [comment]
@parkerrobbins @conbainbridge - try upgrading to v1.1.5 and see if that works for you. There isn't any new code. I think I just published a new version without running `yarn build` first.

If it looks good, please close.

**Comment by conbainbridge** [comment]
@jkhartshorne It's there for me now! @parkerrobbins ?

**Comment by parkerrobbins** [comment]
All good!
